### ISSUE TITLE
Re-use styles and components (header, footer, buttons) from sponsoring site

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#9]
We have to figure out how to re-use the styles, markup, svg assets, entire components from sponsoring.cssconf.eu.
They design uses the same colors, grid, building blocks for both websites, so we should avoid maintaining two versions of each.

@usefulthink @sfrdmn @lukaszklis Any ideas?

**Comment by Kriesse** [comment]
One thought: All css, svg assets, styleguide, main components should live in this repo, as this one will change more often and eventually become more complex, and is also public.

We then need to figure out how to reuse all those things in sponsoring.cssconf.eu.

**Comment by usefulthink** [comment]
I think the thing we should do is to fully reuse all stylesheet-files. For that the styles and html need to be written in a way that makes them work on both sites. The overhead caused by unused styles should be negligible.

As for the source-code management, I currently can't think of an easy option.

following options come to mind:
- moving all shared code into a seperate repository. This will include stylesheets, some js, jekyll-templates and partials, basically most of it
- use the same repository for both sites, so development happens in the 2017.cssconf.eu repository and the sponsoring-repo will just rename sponsoring.html to index.html and add the sponsorship-offer files

(I would prefer the second variant, as this seems to simplify the development-workflow and would not require manual syncing)

**Comment by usefulthink** [comment]
Here’s my current vision for that in example (assuming we use just one repository for both the main- and the sponsoring-site):
- a contribution for is made in branch `2017.cssconf.eu#awesome-stuff`, a PR is created
- after review of the PR it is merged into `master`
- commits to master will trigger a travis build (possible only for public repos, which 2017.cssconf.eu is):
  - travis will create all build-artifacts and commit the new build into the gh-pages
  - at the same time it will update the sponsoring-repo (still required to have the seperate subdomain) by copying over all files, renaming sponsoring.html to index.html and removing other unneeded html-files. The sponsorship-offers that are also in that repository will remain untouched. That should give us the fully working sponsoring-site.

For development that would mean that we only use the `2017.cssconf.eu`-repo. When working on the sponsoring site, we’ll simply open `localhost:2017/sponsoring.html`.

**Comment by Kriesse** [comment]
Started working on this with @lukaszklis and @Lucie-H – we set up a repo for all assets here:
https://github.com/cssconf/2017-assets

Idea is to have all assets live in there and be used by both the main and the sponsoring website.

**Comment by Kriesse** [comment]
done, closing
